//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnExponat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnExponat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap outoforder {
            get {
                object obj = ResourceManager.GetObject("outoforder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap splashscreen {
            get {
                object obj = ResourceManager.GetObject("splashscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;texty&gt;
        ///
        ///&lt;homeBtn lang=&quot;cs&quot;&gt;Domů&lt;/homeBtn&gt;
        ///&lt;howtoBtn lang=&quot;cs&quot;&gt;Jak na to?&lt;/howtoBtn&gt;
        ///&lt;infoBtn lang=&quot;cs&quot;&gt;Info&lt;/infoBtn&gt;
        ///&lt;tipsBtn lang=&quot;cs&quot;&gt;Tipy&lt;/tipsBtn&gt;
        ///
        ///&lt;homeBtn lang=&quot;en&quot;&gt;Home&lt;/homeBtn&gt;
        ///&lt;howtoBtn lang=&quot;en&quot;&gt;How to?&lt;/howtoBtn&gt;
        ///&lt;infoBtn lang=&quot;en&quot;&gt;Info&lt;/infoBtn&gt;
        ///&lt;tipsBtn lang=&quot;en&quot;&gt;Tips&lt;/tipsBtn&gt;
        ///
        ///&lt;homeBtn lang=&quot;de&quot;&gt;Daheim&lt;/homeBtn&gt;
        ///&lt;howtoBtn lang=&quot;de&quot;&gt;Wie zu?&lt;/howtoBtn&gt;
        ///&lt;infoBtn lang=&quot;de&quot;&gt;Info&lt;/infoBtn&gt;
        ///&lt;tipsBtn lang=&quot;de&quot;&gt;Tipps&lt;/tipsBtn&gt;
        ///
        ///&lt;howtoTitle lang=&quot;cs&quot;&gt;Jak na to&lt;/howtoTitle&gt;
        ///&lt;inf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string texts {
            get {
                return ResourceManager.GetString("texts", resourceCulture);
            }
        }
    }
}
